M2.el
Temporarily reverting the slow regexp in #7.
@DanGrayson please don't merge pull requests when there's an ongoing review. I was in the middle of testing why the new regexp hangs my emacs randomly.
=> revert a slow regexp search

M2.el
Partially fixes Macaulay2/M2#1805
=> Restrict infoHelp support to M2-comint-mode

M2.el
This lets us take advantage of various built-in indentation features.
In particular, `M-x indent-region` (or `C-M \`) works to indent an
entire region.
=> Set indent-line-function instead of defining TAB behavior directly

M2.el
It is currently bound to `M2-newline-and-indent`, which calls
`newline` and then indents.  However, `newline` by itself already
indents the next line (provided that the user has
`electric-indent-mode` enabled, which is the default), and so calling
this specialized function is unnecessary.  Furthermore, C-m is already
bound to `newline` in `global-map`, so there's no reason to bind it
again.
Also, if the user has turned off `electric-indent-mode`, then C-m will
have the desired behavior -- no electric indents.
=> Newline and indent updates

M2.el
They're still incomplete (in particular, SimpleDoc strings aren't
supported), so we revert these changes for now to avoid any surprises
to users installing Macaulay2 1.18 after it is released.
=> Revert recent newline/indent changes

M2.el
`new-frame` was [made obsolete](https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/frame.el?id=f7df88f) in Emacs 22 and [removed](https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/frame.el?id=f1c48b0) in Emacs 27.
=> Use make-frame in M2-demo instead of new-frame

M2.el
These menus may be useful for users to discover what functions are available in the two Macaulay2 major modes and to quickly learn their keybindings.
The menus include all functions marked `interactive`.  Functions that have a corresponding keybinding in `M2-mode` only are only displayed in the `M2-mode` menu, and similar for `M2-comint-mode`.  Functions that have a corresponding keybinding in both modes are displayed in both menus.
There are some exceptions to this:
* `M2` is bound to f12 in both modes, but really only makes sense in the `M2-mode` menu.
* `M2-send-to-program` is bound to f11 in both modes, but makes the most sense in the `M2-mode` menu, as
`M2-send-to-program-or-jump-to-source-code` serves a similar purpose in `M2-comint-mode`.
* `M2-dynamic-complete-symbol` is marked …
=> Add menus to M2-mode and M2-comint-mode

M2-symbols.el.in
Instead of using regular expressions and `font-lock-keywords` for syntax highlighting strings and comments, we use [syntactic fontification](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntactic-Font-Lock.html).  Syntax tables are already set up for comments and `"`-delimited strings, so the only thing to add support for is `///`-delimited strings.
*Note*: For now, this will break syntax highlighting inside `doc` and `TEST`.
This may help with https://github.com/Macaulay2/M2/issues/2522.
=> Use syntactic fontification for comments and strings

M2.el
This is an alternative to #36:
- Match file positions of the form -*Foo[...]*- for any "Foo"
cc: @d-torrance
=> File position matching changes

M2.el
This has a number of advantages:
* File positions are underlined and colorized (red for errors, green otherwise)
* The mouse may also be used to jump to source
* Support for Compilation mode keybindings like ``C-x ` `` for next-error
* No need for the function `M2-jump-to-source`, so it has been removed
The function `M2-send-to-program-or-jump-to-source-code` is now only a very thin wrapper around `comint-send-input` and has been renamed to `M2-send-input`.
The regular expressions for matching file positions have been simplified.  More file positions should be clickable than were before, e.g., entries in the "location of symbol" column given by `listSymbols`.  (This has been tested against the changes in https://github.com/Macaulay2/M2/pull/2760).
=> Use compilation-shell-minor-mode for jumping to source

M2.el
We only need the side effects and not a list of the results.  This fixes a warning when byte-compiling.
=> Use "mapc" instead of "mapcar" for setting mode maps & syntax tables

M2.el
These commits fix the following warnings when running `M-x byte-compile-file` on `M2.el`:
```
In M2-dynamic-complete-symbol:
M2.el:309:15:Warning: ‘comint-dynamic-simple-complete’ is an obsolete function
(as of 24.1); use ‘completion-in-region’ instead.
M2.el:403:1:Warning: Unused lexical variable ‘db’
In M2--send-to-program-helper:
M2.el:411:27:Warning: Use ‘with-current-buffer’ rather than
save-excursion+set-buffer
M2.el:515:1:Warning: Unused lexical variable ‘height’
M2.el:515:1:Warning: Unused lexical variable ‘width’
In M2-demo:
M2.el:536:30:Warning: ‘make-variable-buffer-local’ not called at toplevel
M2.el:538:34:Warning: Use ‘with-current-buffer’ rather than
save-excursion+set-buffer
In M2-this-line-indent-amount:
M2.el:577:12:Warning: ‘previous-line’ is for interactive use only; …
```
=> Fix warnings when byte-compiling

M2.el
By default, we turn the new `M2-blink-region-flag` variable (which determines whether we highlight the evaluated region for a moment, inspired by ESS -- see #38) on.
Also, we add a new function, `M2-toggle-blink-region-flag` to toggle the value of this variable and add a menu entry that calls this function.
=> M2-blink-region-flag updates

M2.el
Our regular expressions flag any string ending in ":[0-9]+:[0-9]+" as a file location, including timestamps, e.g. the one in version#"compile time".
We add a new element to compilation-transform-file-match-alist so that compilation mode knows not to make any filenames consisting of two digits (i.e., the hour, since the minute and seconds are interpreted as row and column number) clickable.
=> Don't flag timestamps as file locations

M2.el
Filenames are frequently surrounded by square brackets because of net(Function).  We were omitting the opening square bracket from the regex in one of the three cases, but not all, which was leading to some incorrect behavior.
---
This fixes the issue I mentioned in https://github.com/Macaulay2/M2/pull/3026#issue-2025171322 .  In particular, consider the code below:
```m2
i1 : x -> x
o1 = -*Function[stdio:1:2-1:5]*-
o1 : FunctionClosure
```
Currently, the second regex (which already doesn't allow `[`) matches `stdio:1:2-1:5`, but sees that the filename is `stdio`, which is  blacklisted, so we move to the third regex (which has been allowing `[`), and that thinks that the filename is `-*Function[stdio`, which is obviously incorrect.
So we omit `[` from the third regex (which is for …
=> Don't match filenames with opening bracket in regex

M2.el
When run inside Emacs, `infoHelp` prints a little message to tell Emacs how to open the appropriate info file using `info.el`.  But the user doesn't need to see that, so we remove it.
```m2
i1 : infoHelp "ideal"
-* infoHelp: (Macaulay2Doc)ideal *-
i2 : 
```
```m2
i1 : infoHelp "ideal"
i2 : 
```
=> Remove "infoHelp" cruft from output

M2.el
This is an improved version of #18, which was eventually reverted (#22).  The proposal is to keep the same basic behavior of indentation in `M2-mode`, but with a few improvements:
* `M2-electric-tab` now checks to see if it was called from `newline`, and if it was, replicates the behavior of `M2-newline-and-indent`.  This means that we can deprecate `M2-newline-and-indent` and just use `newline`, which is great because it has a lot more features.  For example, users can now turn off automatic indentation after pressing <kbd>Return</kbd> by disabling `electric-indent-mode`.
* Previously, we cleaned up the whitespace while indenting in one case (when the current indentation was further than it should have been and we had to move it back), but now we clean it up in all cases.  So for …
=> Indentation updates

M2.el
The only difference is that we were forcing `comint-use-prompt-regexp` to be `t`, but sending code to Macaulay2 works just fine whether it's `t` or `nil`.  The value determines whether we send just a single line or the entire input field to the M2 process when scrolling up to previous inputs and pressing <kbd>Return</kbd>.  Let's let the user choose the desired behavior by setting `comint-use-prompt-regexp` to `t` if they choose.  (It defaults to `nil` globally).
Here's an example.  Suppose we enter the following (using <kbd>C</kbd>-<kbd>j</kbd> for the newlines), and then call `comint-send-input`:
```m2
i1 : 1
2
3
o1 = 1
i2 : 
o2 = 2
i3 : 
o3 = 3
```
Now suppose we scroll up to the very first line with `comint-use-regexp` set to `nil` and call `comint-send-input`.  We get all three …
=> Deprecate M2-send-input in favor of comint-send-input

M2.el
One thing that I broke in a recent pull request (probably #52) was preserving indentation between blank lines.
For example, suppose we have something like the following:
```m2
f = x -> (
x + 2)
```
We want the `x + 2` indented since it's inside the parentheses.  But currently, when Emacs is determining the indentation of the third line, it looks back to the second line, sees that there's nothing there, and figures that there should be no indentation.  So we end up with:
```m2
f = x -> (
x + 2)
```
With this PR, we keep going back until we either hit a non-blank line or the beginning of the buffer to determine the indentation.
We also add a docstring to the `M2-this-line-indent-amount` function.
Cc: @DanGrayson
=> Determine indentation based on the last non-blank line

M2.el
It turns out that I broke the Macaulay2 demo feature described in the [running Macaulay2 in emacs](https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_running_sp__Macaulay2_spin_spemacs.html) documentation node much earlier than I thought.  Way back in #42, I deleted the line that set the current buffer as the demo buffer.  So it's been broken since the release of 1.22.  Oops!
This PR restores the behavior as described in the documentation and from what I've observed running Macaulay2 1.19.1 in Ubuntu 22.04.  However, it's implemented a bit differently.
Previously, this code was just one case inside a much larger `M2-send-to-program` function, which was bound to <kbd>F11</kbd> in both `M2-mode` and `M2-comint-mode`.  But since #54, `M2-send-to-program` is only meant …
=> Restore F11 behavior of copying code from the demo buffer in M2-comint-mode

M2.el
This will allow us to jump to code in files with spaces in their paths.
In particular, the filename regex used by Compilation Mode now recognizes files that either:
* Contain no spaces at all (the current behavior)
* Contain any character but are enclosed in double quotes (which will be the case for filenames containing spaces if [Macaulay2/M2#3137](https://github.com/Macaulay2/M2/pull/3137) is merged)
Thanks to my Piedmont colleague @rjlutz for the idea of using double quotes to solve the problem of identifying when spaces might belong to a filename!
If this is accepted, then I'll update the M2-emacs submodule commit in https://github.com/Macaulay2/M2/pull/3137.
Cc: @mikestillman 
Closes: #48
=> Look for filenames enclosed in double quotes

M2.el
I'm not sure how this happened -- probably not being careful with git on my part -- but somehow two of the updated lines from #59 were placed *after* the line they were supposed to go *before*. 
This resulted in the following error when byte-compiling:
```elisp
In toplevel form:
M2-mode.el:11:2: Error: Invalid function: "\\(?:\\(?1:[^\\[:
]+\\)\\|\"\\(?1:.+\\)\"\\):\\([0-9]+\\):\\([0-9]+\\)"
```
=> Fix lines that somehow got transposed in compilation mode regex list

M2.el
Prior to Macaulay2 1.22, errors that occurred in the startupString code (when M2 was built using autotools) printed a nonexistent file location (Macaulay2/Core/startup.m2.in), and so we told compilation mode not to link to it when these errors occurred. But this is no longer an issue.
=> Remove old startup.m2.in path from ignored filenames

M2.el
This restores the original behavior of sending code to the M2 process when the last line in the source file is nonempty.
One difference between this and the original behavior is that we do not add a newline when the last line is empty.
Closes: #69
=> Add newline when at end of file in M2-send-to-program

M2.el
This flushes compilation mode's cache so that we don't jump to the wrong location after modifying and reloading a source file.
Closes: #65
=> Call compilation-forget-errors when sending input to M2 process

M2.el
In particular, compilation mode will only recognize paths containing alphanumeric characters, `/`, `.`, `_`, and `-` (or, as before, paths enclosed in double quotes which will happen when they contain a space).  This should catch the vast majority of paths so we don't need to worry about creating a specific blacklist for things like spaces, `[`, `{`, `|`, etc.
Closes: #71
=> Only match filenames using POSIX portable filename character set

M2.el
Previously, we sent a closing *- or " at *every* new line when we were still inside a comment or string, which messes things up when entering multiple lines of input.
Note that we hardcode the regex instead of using `M2-comint-prompt-regexp`, since it also matches output prompts.
This fixes the issue brought up in https://github.com/Macaulay2/M2-emacs/pull/82#issuecomment-2821576885.
=> Only "fix" unclosed strings when we've received a new input prompt
